// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMC69WXuiKXSNVniAEI2gqKpCwSDgANw',
    appId: '1:43030776746:web:0ab96e14017554acdcf9d3',
    messagingSenderId: '43030776746',
    projectId: 'mynotes-8ae1f',
    authDomain: 'mynotes-8ae1f.firebaseapp.com',
    storageBucket: 'mynotes-8ae1f.appspot.com',
    measurementId: 'G-EHRYF4GRTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimygfr3DJW7z2BF2ucFCu9W9n2yL9Pds',
    appId: '1:43030776746:android:954e55f4532aac38dcf9d3',
    messagingSenderId: '43030776746',
    projectId: 'mynotes-8ae1f',
    storageBucket: 'mynotes-8ae1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_8-Pch0HaH-ZrE4cen3WGvysYmZdCDw',
    appId: '1:43030776746:ios:d2dad008c1a9f03fdcf9d3',
    messagingSenderId: '43030776746',
    projectId: 'mynotes-8ae1f',
    storageBucket: 'mynotes-8ae1f.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0_8-Pch0HaH-ZrE4cen3WGvysYmZdCDw',
    appId: '1:43030776746:ios:d2dad008c1a9f03fdcf9d3',
    messagingSenderId: '43030776746',
    projectId: 'mynotes-8ae1f',
    storageBucket: 'mynotes-8ae1f.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBMC69WXuiKXSNVniAEI2gqKpCwSDgANw',
    appId: '1:43030776746:web:3fcef33f20ae9e50dcf9d3',
    messagingSenderId: '43030776746',
    projectId: 'mynotes-8ae1f',
    authDomain: 'mynotes-8ae1f.firebaseapp.com',
    storageBucket: 'mynotes-8ae1f.appspot.com',
    measurementId: 'G-HQ3NDF1J97',
  );
}
